apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent-bit
spec:
  releaseName: fluent-bit
  chart:
    spec:
      chart: fluent-bit
      sourceRef:
        kind: HelmRepository
        name: fluent-bit
        namespace: flux-system
      version: "0.19.21"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/fluent/helm-charts/blob/main/charts/fluent-bit/values.yaml
#  values:

